# Generated by Django 2.2 on 2020-10-19 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('date_founded', models.DateField(verbose_name='Foundation date')),
                ('webpage', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ram_gb', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='RAM memory in GB')),
                ('storage_gb', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Storage in GB')),
                ('screen_inches', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Screen size in inches')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.Manufacturer')),
            ],
        ),
    ]
